apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deploy-fluxed
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myip
        image: cloudnativelabs/whats-my-ip
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
