apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: no-ns-deploy
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myip
        image: cloudnativelabs/whats-my-ip
        ports:
        - containerPort: 8080
